--<ScriptOptions statementTerminator="GO"/>

CREATE SCHEMA "stg"
GO

CREATE TABLE "stg"."CM_EXT_DIM_BARRIO" (
		"CD_BARRIO" VARCHAR(20) NOT NULL,
		"NM_BARRIO" VARCHAR(150) NOT NULL,
		"CD_SECTOR_GEOGRAFICO" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_DIA_FERIADO" (
		"CD_DIA_FERIADO" VARCHAR(20) NOT NULL,
		"NM_DIA_FERIADO" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_FECHA" (
		"SK_FC" NUMERIC(18 , 0) NULL,
		"NM_FC" VARCHAR(100) NULL,
		"AÑO" DATETIME NULL,
		"NM_AÑO" VARCHAR(100) NULL,
		"SEMESTRE" DATETIME NULL,
		"NM_SEMESTRE" VARCHAR(100) NULL,
		"TRIMESTRE" DATETIME NULL,
		"NM_TRIMESTRE" VARCHAR(100) NULL,
		"MES" DATETIME NULL,
		"NM_MES" VARCHAR(100) NULL,
		"SEMANA" INT NULL,
		"NM_SEMANA" VARCHAR(100) NULL,
		"DIA_AÑO" INT NULL,
		"NM_DIA_AÑO" VARCHAR(100) NULL,
		"DIA_SEMESTRE_AÑO" INT NULL,
		"NM_DIA_SEMESTRE_AÑO" VARCHAR(100) NULL,
		"DIA_TRIMESTRE" INT NULL,
		"NM_DIA_TRIMESTRE" VARCHAR(100) NULL,
		"DIA_MES" INT NULL,
		"NM_DIA_MES" VARCHAR(100) NULL,
		"DIA_SEMANA" INT NULL,
		"NM_DIA_SEMANA" VARCHAR(100) NULL,
		"SEMANA_AÑO" INT NULL,
		"NM_SEMANA_AÑO" VARCHAR(100) NULL,
		"MES_AÑO" INT NULL,
		"NM_MES_AÑO" VARCHAR(100) NULL,
		"MES_SEMESTRE_AÑO" INT NULL,
		"NM_MES_SEMESTRE_AÑO" VARCHAR(100) NULL,
		"MES_TRIMESTRE" INT NULL,
		"NM_MES_TRIMESTRE" VARCHAR(100) NULL,
		"TRIMESTRE_AÑO" INT NULL,
		"NM_DEL_TRIMESTRE_AÑO" VARCHAR(100) NULL,
		"TRIMESTRE_SEMESTRE_AÑO" INT NULL,
		"NM_TRIMESTRE_SEMESTRE_AÑO" VARCHAR(100) NULL,
		"SEMESTRE_AÑO" INT NULL,
		"NM_SEMESTRE_AÑO" VARCHAR(100) NULL,
		"AÑO_FISCAL" DATETIME NULL,
		"NM_AÑO_FISCAL" VARCHAR(100) NULL,
		"SEMESTRE_FISCAL" DATETIME NULL,
		"NM_SEMESTRE_FISCAL" VARCHAR(100) NULL,
		"TRIMESTRE_FISCAL" DATETIME NULL,
		"NM_TRIMESTRE_FISCAL" VARCHAR(100) NULL,
		"MES_FISCAL" DATETIME NULL,
		"NM_MES_FISCAL" VARCHAR(100) NULL,
		"SEMANA_FISCAL" DATETIME NULL,
		"NM_SEMANA_FISCAL" VARCHAR(100) NULL,
		"DIA_FISCAL" DATETIME NULL,
		"NM_DIA_FISCAL" VARCHAR(100) NULL,
		"DIA_AÑO_FISCAL" INT NULL,
		"NM_DIA_AÑO_FISCAL" VARCHAR(100) NULL,
		"DIA_SEMESTRE_AÑO_FISCAL" INT NULL,
		"NM_DIA_SEMESTRE_AÑO_FISCAL" VARCHAR(100) NULL,
		"DIA_TRIMESTRE_FISCAL" INT NULL,
		"NM_DIA_TRIMESTRE_FISCAL" VARCHAR(100) NULL,
		"DIA_MES_FISCAL" INT NULL,
		"NM_DIA_MES_FISCAL" VARCHAR(100) NULL,
		"DIA_SEMANA_FISCAL" INT NULL,
		"NM_DIA_SEMANA_FISCAL" VARCHAR(100) NULL,
		"SEMANA_AÑO_FISCAL" INT NULL,
		"NM_SEMANA_AÑO_FISCAL" VARCHAR(100) NULL,
		"MES_AÑO_FISCAL" INT NULL,
		"NM_MES_AÑO_FISCAL" VARCHAR(100) NULL,
		"MES_SEMESTRE_AÑO_FISCAL" INT NULL,
		"NM_MES_SEMESTRE_AÑO_FISCAL" VARCHAR(100) NULL,
		"MES_TRIMESTRE_FISCAL" INT NULL,
		"NM_MES_TRIMESTRE_FISCAL" VARCHAR(100) NULL,
		"TRIMESTRE_AÑO_FISCAL" INT NULL,
		"NM_DEL_TRIMESTRE_AÑO_FISCAL" VARCHAR(100) NULL,
		"TRIMESTRE_SEMESTRE_AÑO_FISCAL" INT NULL,
		"NM_TRIMESTRE_SEMESTRE_AÑO_FISCAL" VARCHAR(100) NULL,
		"SEMESTRE_AÑO_FISCAL" INT NULL,
		"NM_SEMESTRE_AÑO_FISCAL" VARCHAR(100) NULL,
		"CD_DIA_FERIADO" VARCHAR(20) NOT NULL,
		"INDICADOR_DIA_LABORAL" INT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_LOCALIZACION_GEOGRAFICA" (
		"CD_LOCALIZACION_GEOGRAFICA" VARCHAR(20) NOT NULL,
		"CD_BARRIO" VARCHAR(20) NOT NULL,
		"CD_SECTOR_GEOGRAFICO" VARCHAR(20) NOT NULL,
		"CD_MUNICIPIO" VARCHAR(20) NOT NULL,
		"CD_PROVINCIA" VARCHAR(20) NOT NULL,
		"CD_REGION" VARCHAR(20) NOT NULL,
		"CD_PAIS" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_MUNICIPIO" (
		"CD_MUNICIPIO" VARCHAR(20) NOT NULL,
		"NM_MUNICIPIO" VARCHAR(150) NOT NULL,
		"INDICADOR_MUNICIPIO_CABECERA" CHAR(1) NULL,
		"CD_PROVINCIA" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_PAIS" (
		"CD_PAIS" VARCHAR(20) NOT NULL,
		"NM_PAIS" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_PERIODO" (
		"CD_PERIODO" VARCHAR(20) NOT NULL,
		"DESC_PERIODO" VARCHAR(100) NULL,
		"CD_PERIODO_ANTERIOR" VARCHAR(20) NULL,
		"CD_TIPO_PERIODO" VARCHAR(20) NOT NULL,
		"FC_INI_PERIODO" DATETIME NULL,
		"FC_FIN_PERIODO" DATETIME NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_PROVINCIA" (
		"CD_PROVINCIA" VARCHAR(20) NOT NULL,
		"NM_PROVINCIA" VARCHAR(150) NOT NULL,
		"SIGLA_PROVINCIA" VARCHAR(20) NULL,
		"CD_REGION" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_REGION" (
		"CD_REGION" VARCHAR(20) NOT NULL,
		"NM_REGION" VARCHAR(150) NOT NULL,
		"CD_MACROREGION" VARCHAR(20) NOT NULL,
		"NM_MACROREGION" VARCHAR(150) NOT NULL,
		"CD_PAIS" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_SECTOR_GEOGRAFICO" (
		"CD_SECTOR_GEOGRAFICO" VARCHAR(20) NOT NULL,
		"NM_SECTOR_GEOGRAFICO" VARCHAR(150) NOT NULL,
		"CD_MUNICIPIO" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_TIPO_DIRECCION" (
		"CD_TIPO_DIRECCION" VARCHAR(20) NOT NULL,
		"DESC_TIPO_DIRECCION" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_TIPO_PERIODO" (
		"CD_TIPO_PERIODO" VARCHAR(20) NULL,
		"DESC_TIPO_PERIODO" VARCHAR(100) NULL
	)
GO

CREATE TABLE "stg"."CM_EXT_DIM_VIA_CONTACTO" (
		"CD_VIA_CONTACTO" VARCHAR(20) NOT NULL,
		"DESC_VIA_CONTACTO" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_CARGO" (
		"CD_CARGO" VARCHAR(20) NOT NULL,
		"DESC_CARGO" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_CATEGORIA_PUESTO" (
		"CD_CATEGORIA_PUESTO" VARCHAR(20) NOT NULL,
		"DESC_CATEGORIA_PUESTO" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_CATEGORIA_SALARIAL" (
		"CD_CATEGORIA_SALARIAL" VARCHAR(20) NOT NULL,
		"DESC_CATEGORIA_SALARIAL" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_CENTRO_COSTO" (
		"CD_CENTRO_COSTO" VARCHAR(20) NOT NULL,
		"DESC_CENTRO_COSTO" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_DEPARTAMENTO" (
		"CD_DEPARTAMENTO" VARCHAR(20) NOT NULL,
		"DESC_DEPARTAMENTO" VARCHAR(100) NOT NULL,
		"CD_CENTRO_COSTO" VARCHAR(20) NOT NULL,
		"CD_DEPARTAMENTO_PADRE" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_EMPLEADO" (
		"CD_EMPLEADO" VARCHAR(20) NOT NULL,
		"CD_TIPO_INDENTIFICACION" VARCHAR(20) NOT NULL,
		"DOC_IDENTIFICACION" VARCHAR(20) NOT NULL,
		"FC_INGRESO" DATETIME NOT NULL,
		"CD_CARGO" VARCHAR(20) NOT NULL,
		"CD_ESTATUS_EMPLEADO" VARCHAR(20) NOT NULL,
		"CD_CATEGORIA_SALARIAL" VARCHAR(20) NOT NULL,
		"CD_DEPARTAMENTO" VARCHAR(20) NOT NULL,
		"CD_EMPRESA" VARCHAR(20) NOT NULL,
		"CD_PUESTO" VARCHAR(20) NOT NULL,
		"CD_TIPO_CONTRATO_TRABAJO" VARCHAR(20) NOT NULL,
		"SALARIO_BASE" NUMERIC(20 , 2) NULL,
		"MONTO_BENEFICIOS" NUMERIC(20 , 2) NULL,
		"MONTO_NETO_EMPLEADO_NOM_BASE" NUMERIC(20 , 2) NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_EMPRESA" (
		"CD_EMPRESA" VARCHAR(20) NOT NULL,
		"DESC_EMPRESA" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_ESTADO_CIVIL" (
		"CD_ESTADO_CIVIL" VARCHAR(20) NOT NULL,
		"DESC_ESTADO_CIVIL" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_ESTATUS_EMPLEADO" (
		"CD_ESTATUS_EMPLEADO" VARCHAR(20) NOT NULL,
		"DESC_ESTATUS_EMPLEADO" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_FAMILIA_PUESTO" (
		"CD_FAMILIA_PUESTO" VARCHAR(20) NOT NULL,
		"DESC_FAMILIA_PUESTO" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_GENERO" (
		"CD_GENERO" VARCHAR(20) NOT NULL,
		"DESC_GENERO" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_NIVEL_EDUCATIVO" (
		"CD_NIVEL_EDUCATIVO" VARCHAR(20) NOT NULL,
		"DESC_NIVEL_EDUCATIVO" VARCHAR(150) NOT NULL,
		"ORDEN_NIVEL_EDUCATIVO" VARCHAR(150) NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_OCUPACION" (
		"CD_OCUPACION" VARCHAR(20) NOT NULL,
		"DESC_OCUPACION" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_OFICINA" (
		"CD_OFICINA" VARCHAR(20) NOT NULL,
		"DESC_OFICINA" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_PERSONA" (
		"CD_TIPO_INDENTIFICACION" VARCHAR(20) NOT NULL,
		"DOC_IDENTIFICACION" VARCHAR(20) NOT NULL,
		"NM_PERSONA" VARCHAR(150) NOT NULL,
		"FC_NACIMIENTO" DATETIME NOT NULL,
		"CD_RANGO_EDAD" VARCHAR(20) NOT NULL,
		"FC_INGRESO" DATETIME NOT NULL,
		"CD_PROFESION" VARCHAR(20) NOT NULL,
		"CD_OCUPACION" VARCHAR(20) NOT NULL,
		"CD_NIVEL_EDUCATIVO" VARCHAR(20) NOT NULL,
		"CD_TIPO_RELIGION" VARCHAR(20) NOT NULL,
		"CD_TIPO_RESIDENCIA" VARCHAR(20) NOT NULL,
		"CD_ESTADO_CIVIL" VARCHAR(20) NOT NULL,
		"CD_GENERO" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_PROFESION" (
		"CD_PROFESION" VARCHAR(20) NOT NULL,
		"DESC_PROFESION" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_PUESTO" (
		"CD_PUESTO" VARCHAR(20) NOT NULL,
		"DESC_PUESTO" VARCHAR(100) NOT NULL,
		"CD_CATEGORIA_PUESTO" VARCHAR(20) NOT NULL,
		"CD_FAMILIA_PUESTO" VARCHAR(20) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_RANGO_EDAD" (
		"CD_RANGO_EDAD" VARCHAR(20) NOT NULL,
		"DESC_RANGO_EDAD" VARCHAR(100) NOT NULL,
		"VALOR_INI_RANGO" NUMERIC(10 , 2) NOT NULL,
		"VALOR_FIN_RANGO" NUMERIC(10 , 2) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_SECTOR_ECONOMICO" (
		"CD_SECTOR_ECONOMICO" VARCHAR(20) NOT NULL,
		"DESC_SECTOR_ECONOMICO" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_TIPO_CONTRATO_TRABAJO" (
		"CD_TIPO_CONTRATO_TRABAJO" VARCHAR(20) NOT NULL,
		"DESC_TIPO_CONTRATO_TRABAJO" VARCHAR(100) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_TIPO_IDENTIFICACION" (
		"CD_TIPO_INDENTIFICACION" VARCHAR(20) NOT NULL,
		"DESC_TIPO_IDENTIFICACION" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_TIPO_RELIGION" (
		"CD_TIPO_RELIGION" VARCHAR(20) NOT NULL,
		"DESC_TIPO_RELIGION" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_DIM_TIPO_RESIDENCIA" (
		"CD_TIPO_RESIDENCIA" VARCHAR(20) NOT NULL,
		"DESC_TIPO_RESIDENCIA" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_FACT_PERFIL_EMPLEADO" (
		"FC_REFERENCIA" DATETIME NOT NULL,
		"CD_EMPLEADO" VARCHAR(20) NOT NULL,
		"FC_INGRESO" DATETIME NOT NULL,
		"CD_CARGO" VARCHAR(20) NOT NULL,
		"CD_ESTATUS_EMPLEADO" VARCHAR(20) NOT NULL,
		"CD_CATEGORIA_SALARIAL" VARCHAR(20) NOT NULL,
		"CD_DEPARTAMENTO" VARCHAR(20) NOT NULL,
		"CD_EMPRESA" VARCHAR(20) NOT NULL,
		"CD_PUESTO" VARCHAR(20) NOT NULL,
		"CD_TIPO_CONTRATO_TRABAJO" VARCHAR(20) NOT NULL,
		"CD_TIPO_INDENTIFICACION" VARCHAR(20) NOT NULL,
		"DOC_IDENTIFICACION" VARCHAR(20) NOT NULL,
		"NM_PERSONA" VARCHAR(150) NOT NULL,
		"FC_NACIMIENTO" DATETIME NOT NULL,
		"CD_RANGO_EDAD" VARCHAR(20) NOT NULL,
		"CD_ESTADO_CIVIL" VARCHAR(20) NOT NULL,
		"CD_GENERO" VARCHAR(20) NOT NULL,
		"CD_LOCALIZACION_GEOGRAFICA_RESIDENCIA" VARCHAR(20) NOT NULL,
		"CD_CENTRO_COSTO" VARCHAR(20) NOT NULL,
		"CANTIDAD_EMPLEADO" NUMERIC(10 , 2) NULL,
		"SALARIO_BASE" NUMERIC(20 , 2) NULL,
		"MONTO_BENEFICIOS" NUMERIC(20 , 2) NULL,
		"MONTO_NETO_EMPLEADO_NOM_BASE" NUMERIC(20 , 2) NULL,
		"TIEMPO_EMPLEADO" NUMERIC(10 , 2) NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_REL_DIRECCION_PERSONA" (
		"CD_TIPO_INDENTIFICACION" VARCHAR(20) NOT NULL,
		"DOC_IDENTIFICACION" VARCHAR(20) NOT NULL,
		"CD_TIPO_DIRECCION" VARCHAR(20) NOT NULL,
		"CD_LOCALIZACION_GEOGRAFICA" VARCHAR(20) NOT NULL,
		"CD_BARRIO" VARCHAR(20) NOT NULL,
		"CD_SECTOR_GEOGRAFICO" VARCHAR(20) NOT NULL,
		"CD_MUNICIPIO" VARCHAR(20) NOT NULL,
		"CD_PROVINCIA" VARCHAR(20) NOT NULL,
		"CD_REGION" VARCHAR(20) NOT NULL,
		"CD_PAIS" VARCHAR(20) NOT NULL,
		"DIRECCION_PERSONA" VARCHAR(150) NOT NULL
	)
GO

CREATE TABLE "stg"."PE_EXT_REL_VIA_CONTACTO_PERSONA" (
		"CD_TIPO_INDENTIFICACION" VARCHAR(20) NOT NULL,
		"DOC_IDENTIFICACION" VARCHAR(20) NOT NULL,
		"CD_VIA_CONTACTO" VARCHAR(20) NOT NULL,
		"DESC_CONTACTO_PERSONA" VARCHAR(150) NULL,
		"ORDEN_PRIORIDAD_CONTACTO" NUMERIC(10 , 2) NULL
	)
GO

