--<ScriptOptions statementTerminator="GO"/>

CREATE SCHEMA "RH07"
GO

CREATE TABLE "RH07"."DIM_EQUIPO_CONTROL_ASISTENCIA" (
		"SK_EQUIPO_CONTROL_ASISTENCIA" NUMERIC(18 , 0) NOT NULL,
		"CD_EQUIPO_CONTROL_ASISTENCIA" VARCHAR(20) NOT NULL,
		"SK_EMPRESA" NUMERIC(18 , 0) NOT NULL,
		"CD_EMPRESA" VARCHAR(20) NOT NULL,
		"DESC_EQUIPO_CONTROL_ASISTENCIA" VARCHAR(150) NOT NULL,
		"FC_INI_VAL" DATETIME NOT NULL,
		"FC_FIN_VAL" DATETIME NOT NULL,
		"SK_EJECUCION_CREACION" NUMERIC(18 , 0) NULL,
		"SK_EJECUCION_MODIFICACION" NUMERIC(18 , 0) NULL
	)
GO

CREATE TABLE "RH07"."DIM_TIPO_ASISTENCIA" (
		"SK_TIPO_ASISTENCIA" NUMERIC(18 , 0) NULL,
		"CD_TIPO_ASISTENCIA" VARCHAR(20) NULL,
		"DESC_TIPO_ASISTENCIA" VARCHAR(150) NULL,
		"FC_INI_VAL" DATETIME NULL,
		"FC_FIN_VAL" DATETIME NOT NULL IDENTITY (1,1),
		"SK_EJECUCION_CREACION" NUMERIC(18 , 0) NULL,
		"SK_EJECUCION_MODIFICACION" NUMERIC(18 , 0) NULL
	)
GO

CREATE TABLE "RH07"."DIM_TIPO_CONTROL_ASISTENCIA" (
		"SK_TIPO_CONTROL_ASISTENCIA" NUMERIC(18 , 0) NOT NULL,
		"CD_TIPO_CONTROL_ASISTENCIA" VARCHAR(20) NOT NULL,
		"SK_EMPRESA" NUMERIC(18 , 0) NOT NULL,
		"CD_EMPRESA" VARCHAR(20) NOT NULL,
		"DESC_TIPO_CONTROL_ASISTENCIA" VARCHAR(150) NOT NULL,
		"FC_INI_VAL" DATETIME NOT NULL,
		"FC_FIN_VAL" DATETIME NOT NULL,
		"SK_EJECUCION_CREACION" NUMERIC(18 , 0) NULL,
		"SK_EJECUCION_MODIFICACION" NUMERIC(18 , 0) NULL
	)
GO

CREATE TABLE "RH07"."FACT_CONTROL_ASISTENCIA" (
		"SK_CONTROL_ASISTENCIA" CHAR(10) NOT NULL,
		"FC_REFERENCIA" CHAR(10) NOT NULL,
		"SK_TIPO_CONTROL_ASISTENCIA" NUMERIC(18 , 0) NOT NULL,
		"CD_TIPO_CONTROL_ASISTENCIA" VARCHAR(20) NOT NULL,
		"SK_EMPLEADO" NUMERIC(18 , 0) NOT NULL,
		"CD_EMPLEADO" VARCHAR(20) NOT NULL,
		"SK_GENERO" NUMERIC(18 , 0) NOT NULL,
		"CD_GENERO" VARCHAR(20) NOT NULL,
		"SK_RANGO_EDAD" NUMERIC(18 , 0) NOT NULL,
		"CD_RANGO_EDAD" VARCHAR(20) NOT NULL,
		"SK_OFICINA" NUMERIC(18 , 0) NOT NULL,
		"CD_OFICINA" VARCHAR(20) NOT NULL,
		"SK_DEPARTAMENTO" NUMERIC(18 , 0) NOT NULL,
		"CD_DEPARTAMENTO" VARCHAR(20) NOT NULL,
		"SK_PUESTO" NUMERIC(18 , 0) NOT NULL,
		"CD_PUESTO" VARCHAR(20) NOT NULL,
		"SK_CARGO" NUMERIC(18 , 0) NOT NULL,
		"CD_CARGO" VARCHAR(20) NOT NULL,
		"SK_CATEGORIA_SALARIAL" NUMERIC(18 , 0) NOT NULL,
		"CD_CATEGORIA_SALARIAL" VARCHAR(20) NOT NULL,
		"SK_EMPRESA" NUMERIC(18 , 0) NOT NULL,
		"CD_EMPRESA" VARCHAR(20) NOT NULL,
		"SK_CENTRO_COSTO" NUMERIC(18 , 0) NOT NULL,
		"CD_CENTRO_COSTO" VARCHAR(20) NOT NULL,
		"SK_FAMILIA_PUESTO" NUMERIC(18 , 0) NOT NULL,
		"CD_FAMILIA_PUESTO" VARCHAR(20) NOT NULL,
		"SK_ESTADO_CIVIL" NUMERIC(18 , 0) NOT NULL,
		"CD_ESTADO_CIVIL" VARCHAR(20) NOT NULL,
		"SK_CATEGORIA_PUESTO" NUMERIC(18 , 0) NOT NULL,
		"CD_CATEGORIA_PUESTO" VARCHAR(20) NOT NULL,
		"SK_PERSONA" NUMERIC(18 , 0) NOT NULL,
		"CD_PERSONA" VARCHAR(20) NOT NULL,
		"FC_ENTRADA" DATETIME NULL,
		"FC_SALIDA" DATETIME NULL,
		"CANTIDAD_HORA" NUMERIC(10 , 0) NULL,
		"SK_EJECUCION_CREACION" NUMERIC(18 , 0) NOT NULL,
		"SK_EJECUCION_MODIFICACION" NUMERIC(18 , 0) NULL
	)
GO

CREATE UNIQUE INDEX "DIM_EQUIPO_CONTROL_ASISTENCIA_CD_EQUIPO_CONTROL_ASISTENCIA_IDX"
	ON "RH07"."DIM_EQUIPO_CONTROL_ASISTENCIA"
	("CD_EQUIPO_CONTROL_ASISTENCIA"		ASC,
	  "FC_INI_VAL"		ASC)
GO

CREATE UNIQUE INDEX "DIM_TIPO_ASISTENCIA_CD_TIPO_ASISTENCIA_IDX"
	ON "RH07"."DIM_TIPO_ASISTENCIA"
	("CD_TIPO_ASISTENCIA"		ASC,
	  "FC_INI_VAL"		ASC)
GO

CREATE UNIQUE INDEX "DIM_TIPO_CONTROL_ASISTENCIA_CD_TIPO_CONTROL_ASISTENCIA_IDX"
	ON "RH07"."DIM_TIPO_CONTROL_ASISTENCIA"
	("CD_TIPO_CONTROL_ASISTENCIA"		ASC,
	  "FC_INI_VAL"		ASC)
GO

CREATE UNIQUE INDEX "FACT_CONTROL_ASISTENCIA_FC_REFERENCIA_IDX"
	ON "RH07"."FACT_CONTROL_ASISTENCIA"
	("FC_REFERENCIA"		ASC)
GO

ALTER TABLE "RH07"."DIM_EQUIPO_CONTROL_ASISTENCIA" ADD CONSTRAINT "DIM_EQUIPO_CONTROL_ASISTENCIA_PK" PRIMARY KEY CLUSTERED
	("SK_EQUIPO_CONTROL_ASISTENCIA")
GO

ALTER TABLE "RH07"."DIM_EQUIPO_CONTROL_ASISTENCIA" ADD CONSTRAINT "DIM_EQUIPO_CONTROL_ASISTENCIA_SK_EQUIPO_CONTROL_ASISTENCIA_UN" UNIQUE
	("SK_EQUIPO_CONTROL_ASISTENCIA",
	 "CD_EQUIPO_CONTROL_ASISTENCIA")
GO

ALTER TABLE "RH07"."DIM_TIPO_ASISTENCIA" ADD CONSTRAINT "DIM_TIPO_ASISTENCIA_PK" PRIMARY KEY CLUSTERED
	("SK_TIPO_ASISTENCIA")
GO

ALTER TABLE "RH07"."DIM_TIPO_ASISTENCIA" ADD CONSTRAINT "DIM_TIPO_ASISTENCIA_SK_TIPO_ASISTENCIA_UN" UNIQUE
	("SK_TIPO_ASISTENCIA",
	 "CD_TIPO_ASISTENCIA")
GO

ALTER TABLE "RH07"."DIM_TIPO_CONTROL_ASISTENCIA" ADD CONSTRAINT "DIM_TIPO_CONTROL_ASISTENCIA_PK" PRIMARY KEY CLUSTERED
	("SK_TIPO_CONTROL_ASISTENCIA")
GO

ALTER TABLE "RH07"."DIM_TIPO_CONTROL_ASISTENCIA" ADD CONSTRAINT "DIM_TIPO_CONTROL_ASISTENCIA_SK_TIPO_CONTROL_ASISTENCIA_UN" UNIQUE
	("SK_TIPO_CONTROL_ASISTENCIA",
	 "CD_TIPO_CONTROL_ASISTENCIA")
GO

ALTER TABLE "RH07"."FACT_CONTROL_ASISTENCIA" ADD CONSTRAINT "FACT_CONTROL_ASISTENCIA_PK" PRIMARY KEY CLUSTERED
	("SK_ESTADO_CIVIL",
	 "CD_ESTADO_CIVIL",
	 "SK_CONTROL_ASISTENCIA")
GO

ALTER TABLE "RH07"."FACT_CONTROL_ASISTENCIA" ADD CONSTRAINT "FACT_CONTROL_ASISTENCIA_SK_CONTROL_ASISTENCIA_UN" UNIQUE
	("SK_CONTROL_ASISTENCIA")
GO

ALTER TABLE "RH07"."FACT_CONTROL_ASISTENCIA" ADD CONSTRAINT "FACT_CONTROL_ASISTENCIA_DIM_ESTADO_CIVIL_FK" FOREIGN KEY
	("SK_ESTADO_CIVIL",
	 "CD_ESTADO_CIVIL")
	REFERENCES "RH01"."DIM_ESTADO_CIVIL"
	("SK_ESTADO_CIVIL",
	 "CD_ESTADO_CIVIL")
GO

ALTER TABLE "RH07"."FACT_CONTROL_ASISTENCIA" ADD CONSTRAINT "FACT_CONTROL_ASISTENCIA_DIM_TIPO_CONTROL_ASISTENCIA_FK" FOREIGN KEY
	("SK_TIPO_CONTROL_ASISTENCIA",
	 "CD_TIPO_CONTROL_ASISTENCIA")
	REFERENCES "RH07"."DIM_TIPO_CONTROL_ASISTENCIA"
	("SK_TIPO_CONTROL_ASISTENCIA",
	 "CD_TIPO_CONTROL_ASISTENCIA")
GO

